### ISSUE TITLE
`1pxbat` aborts with `terminate called after throwing an instance of 'std::invalid_argument'` `what():  stoi`.

### ISSUE THREAD

**Issue by dreirund** [diresi/1px#1]
I installed this from the Arch Linux AUR package [`1px-git`](https://aur.archlinux.org/packages/1px-git).

when I run `1pxbat`, it aborts with  
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted
```

Regards!

**Comment by diresi** [comment]
Hi!
Can you tell whether `/sys/class/power_supply/BAT1/capacity` exists and show its content?

**Comment by dreirund** [comment]
On Sat, 15 Jul 2023 06:58:18 -0700, Christoph Rissner
***@***.***> wrote:

> Can you tell whether `/sys/class/power_supply/BAT1/capacity` exists

Does not exist;‌ my battery directory is `/sys/class/power_supply/BAT0/`.

`/sys/class/power_supply/BAT0/capacity` does exist ...

> and show its content?

... and currently shows `84` (current percentage).

**Comment by diresi** [comment]
Well, then that's the reason :)
Maybe I could just use any BAT* there is?

**Comment by diresi** [comment]
Alright, I tried my best, please see whether that works for you.

**Comment by dreirund** [comment]
> Maybe I could just use any BAT* there is?

There can also be several batteries. There are also laptops that have 2 builtin batteries, and one can be removed, and they can be interchanged seperately.

Suggestion:‌ Default to the lowest (or to display all in parallel in different displays), and allow the user to optionally specify manually which to use.

Current solution works for now for _one_ single battery.

**Comment by diresi** [comment]
While that's all true it also sounds like YAGNI to me ;)
Thanks for the report, though!
